#![doc = "Peripheral access API for RUSTY-SOC microcontrollers (generated using svd2rust v0.37.1 ( ))\n\nYou can find an overview of the generated API [here].\n\nAPI features to be included in the [next] svd2rust release can be generated by cloning the svd2rust [repository], checking out the above commit, and running `cargo doc --open`.\n\n[here]: https://docs.rs/svd2rust/0.37.1/svd2rust/#peripheral-api\n[next]: https://github.com/rust-embedded/svd2rust/blob/master/CHANGELOG.md#unreleased\n[repository]: https://github.com/rust-embedded/svd2rust"]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![no_std]
#![cfg_attr(docsrs, feature(doc_cfg))]
#[doc = r"Number available in the NVIC for configuring priority"]
pub const NVIC_PRIO_BITS: u8 = 0;
#[allow(unused_imports)]
use generic::*;
#[doc = r"Common register and bit access and modify traits"]
pub mod generic;
#[cfg(feature = "rt")]
unsafe extern "C" {}
#[doc(hidden)]
#[repr(C)]
pub union Vector {
    pub _handler: unsafe extern "C" fn(),
    pub _reserved: usize,
}
#[cfg(feature = "rt")]
#[doc(hidden)]
#[unsafe(no_mangle)]
pub static __EXTERNAL_INTERRUPTS: [Vector; 0] = [];
#[doc = "Timer0 peripheral (64-bit counter) at 1MHz."]
pub type Timer0 = crate::Periph<timer0::RegisterBlock, 0x0001_0000>;
impl core::fmt::Debug for Timer0 {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Timer0").finish()
    }
}
#[doc = "Timer0 peripheral (64-bit counter) at 1MHz."]
pub mod timer0;
#[doc = "General Purposes Input / Output"]
pub type Gpio = crate::Periph<gpio::RegisterBlock, 0x0001_0400>;
impl core::fmt::Debug for Gpio {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Gpio").finish()
    }
}
#[doc = "General Purposes Input / Output"]
pub mod gpio;
#[doc = "On-board Digital-to-Analog Converter, directly wired to the Audio interface."]
pub type Dac = crate::Periph<dac::RegisterBlock, 0x0001_0800>;
impl core::fmt::Debug for Dac {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Dac").finish()
    }
}
#[doc = "On-board Digital-to-Analog Converter, directly wired to the Audio interface."]
pub mod dac;
#[doc = "On-board Display interface, with hardware Framebuffer (128x128, RGB565)."]
pub type Display = crate::Periph<display::RegisterBlock, 0x0001_7c00>;
impl core::fmt::Debug for Display {
    fn fmt(&self, f: &mut core::fmt::Formatter) -> core::fmt::Result {
        f.debug_struct("Display").finish()
    }
}
#[doc = "On-board Display interface, with hardware Framebuffer (128x128, RGB565)."]
pub mod display;
#[unsafe(no_mangle)]
static mut DEVICE_PERIPHERALS: bool = false;
#[doc = r" All the peripherals."]
#[allow(non_snake_case)]
pub struct Peripherals {
    #[doc = "Timer0"]
    pub timer0: Timer0,
    #[doc = "GPIO"]
    pub gpio: Gpio,
    #[doc = "DAC"]
    pub dac: Dac,
    #[doc = "Display"]
    pub display: Display,
}
impl Peripherals {
    #[doc = r" Returns all the peripherals *once*."]
    #[cfg(feature = "critical-section")]
    #[inline]
    pub fn take() -> Option<Self> {
        critical_section::with(|_| {
            if unsafe { DEVICE_PERIPHERALS } {
                return None;
            }
            Some(unsafe { Peripherals::steal() })
        })
    }
    #[doc = r" Unchecked version of `Peripherals::take`."]
    #[doc = r""]
    #[doc = r" # Safety"]
    #[doc = r""]
    #[doc = r" Each of the returned peripherals must be used at most once."]
    #[inline]
    pub unsafe fn steal() -> Self {
        unsafe { DEVICE_PERIPHERALS = true }
        Peripherals {
            timer0: unsafe { Timer0::steal() },
            gpio: unsafe { Gpio::steal() },
            dac: unsafe { Dac::steal() },
            display: unsafe { Display::steal() },
        }
    }
}
